"""add_provider_to_playlist_track

Revision ID: d5969a68ca93
Revises: 91ef207a854e
Create Date: 2025-12-03 19:44:58.264748

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd5969a68ca93'
down_revision = '91ef207a854e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_tracks', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_tracks', 'provider')
    # ### end Alembic commands ###
